src/BarZ/BarZ/Controllers/BarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BarZ.Data;
using BarZ.Data.Models;

namespace BarZ.Controllers
{
    public class BarsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BarsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Bars
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Bar.Include(b => b.CityOrResort);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Bars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = await _context.Bar
                .Include(b => b.CityOrResort)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bar == null)
            {
                return NotFound();
            }

            return View(bar);
        }

        // GET: Bars/Create
        public IActionResult Create()
        {
            ViewData["CityOrResortId"] = new SelectList(_context.Set<CityOrResort>(), "Id", "Name");
            return View();
        }

        // POST: Bars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,BeginningOfTheWorkDay,EndOfTheWorkDay,Description,FacebookPageUrl,CityOrResortId")] Bar bar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityOrResortId"] = new SelectList(_context.Set<CityOrResort>(), "Id", "Name", bar.CityOrResortId);
            return View(bar);
        }

        // GET: Bars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = await _context.Bar.FindAsync(id);
            if (bar == null)
            {
                return NotFound();
            }
            ViewData["CityOrResortId"] = new SelectList(_context.Set<CityOrResort>(), "Id", "Name", bar.CityOrResortId);
            return View(bar);
        }

        // POST: Bars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,BeginningOfTheWorkDay,EndOfTheWorkDay,Description,FacebookPageUrl,CityOrResortId")] Bar bar)
        {
            if (id != bar.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BarExists(bar.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CityOrResortId"] = new SelectList(_context.Set<CityOrResort>(), "Id", "Name", bar.CityOrResortId);
            return View(bar);
        }

        // GET: Bars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = await _context.Bar
                .Include(b => b.CityOrResort)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bar == null)
            {
                return NotFound();
            }

            return View(bar);
        }

        // POST: Bars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bar = await _context.Bar.FindAsync(id);
            _context.Bar.Remove(bar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BarExists(int id)
        {
            return _context.Bar.Any(e => e.Id == id);
        }
    }
}

src/BarZ/BarZ/Controllers/DestinationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BarZ.Data;
using BarZ.Data.Models;

namespace BarZ.Controllers
{
    public class DestinationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DestinationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Destinations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Destination.ToListAsync());
        }

        // GET: Destinations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destination = await _context.Destination
                .FirstOrDefaultAsync(m => m.Id == id);
            if (destination == null)
            {
                return NotFound();
            }

            return View(destination);
        }

        // GET: Destinations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Destinations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Destination destination)
        {
            if (ModelState.IsValid)
            {
                _context.Add(destination);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(destination);
        }

        // GET: Destinations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destination = await _context.Destination.FindAsync(id);
            if (destination == null)
            {
                return NotFound();
            }
            return View(destination);
        }

        // POST: Destinations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Destination destination)
        {
            if (id != destination.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(destination);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DestinationExists(destination.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(destination);
        }

        // GET: Destinations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destination = await _context.Destination
                .FirstOrDefaultAsync(m => m.Id == id);
            if (destination == null)
            {
                return NotFound();
            }

            return View(destination);
        }

        // POST: Destinations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var destination = await _context.Destination.FindAsync(id);
            _context.Destination.Remove(destination);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DestinationExists(int id)
        {
            return _context.Destination.Any(e => e.Id == id);
        }
    }
}

src/BarZ/BarZ/Views/Shared/EventsPartialView.cshtml
@model IEnumerable<BarZ.Areas.Bar_reviews.Models.Events.ViewModels.EventViewModel>

@foreach (var item in Model)
{
    <div style="border:1px solid lightgray; margin:30px; padding:40px">
        <h1 style="margin-top:-20px">@Html.DisplayFor(modelItem => item.EventName)</h1>
        <div class="font-weight-light">@Html.DisplayFor(modelItem => item.DateAndTime)</div>
        <div class="font-weight-light"><span>At</span> @Html.DisplayFor(modelItem => item.Bar.Name)</div>
        <div style="padding-top:20px; padding-bottom:20px">@Html.DisplayFor(modelItem => item.Info)</div>
        <div>
            @if (item.Fee != null)
            {
                <span style="padding:0px; display:inline">
                    @Html.DisplayNameFor(modelItem => item.Fee) <span>:</span>
                    @Html.DisplayFor(modelItem => item.FeeInDollars)
                </span>
            }
            else
            {
                <span style="padding:20px">Admission free</span>
            }
            <span display:inline" class="btnsViewRight">
                @if (this.User.IsInRole(BarZ.Constants.RolesConstants.AdminRoleName))
                {
                    <a asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <span>|</span>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete </a>
                }
            </span>
        </div>
    </div>
}

src/BarZ/BarZ/Views/Shared/ShowBarsWithFeatureOrInDestinationPartialView.cshtml
@model BarZ.Areas.Bar_reviews.Models.Bars.ViewModels.BarViewModel

<div class="barIndexModel">
    <h2>@Html.DisplayFor(modelItem => Model.Name)</h2>
    <p class="font-weight-light">
        (@Html.DisplayFor(modelItem => Model.Destination.Name))
    </p>

    <img class="rounded mx-auto d-block barPicture" src="@Url.Content(Model.PictureAdress)" alt="BarPicture">

    <hr />

    Work time:
    @Html.DisplayFor(modelItem => Model.BeginningOfTheWorkDay) -
    @Html.DisplayFor(modelItem => Model.EndOfTheWorkDay)<br />

    <span class="description">@Html.DisplayFor(modelItem => Model.Description)<br /></span>
    <a href="@Html.DisplayFor(modelItem => Model.FacebookPageUrl)">Facebook page</a><br />
    <a class="btnsViewRight" asp-action="Details" asp-route-id="@Model.Id">Details</a>
</div>

src/BarZ/BarZ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarZ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header style="background-color: #333">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">BarZ</a>
                <div class="spacer"></div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Bar-reviews" asp-controller="Bars" asp-action="Index">Bars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Bar-reviews" asp-controller="Destinations" asp-action="Index">Destinations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Bar-reviews" asp-controller="Features" asp-action="Index">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Bar-reviews" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Bar-reviews" asp-controller="Bars" asp-action="Search">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BarZ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>