src/BarZ/BarZ/Areas/Bar-reviews/Models/Bars/BindingModels/BarCreateBindingModel.cs
namespace BarZ.Areas.Bar_reviews.Models.Bars.BindingModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    using Microsoft.AspNetCore.Http;

    using BarZ.Data.Models;

    public class BarCreateBindingModel
    {
        [Required]
        [MinLength(2)]
        [MaxLength(64)]
        public string Name { get; set; }

        public IFormFile image { get; set; }

        [DisplayFormat(DataFormatString = "{HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Time)]
        [DisplayName("Open at")]
        public DateTime BeginningOfTheWorkDay { get; set; }

        [DisplayFormat(DataFormatString = "{HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Time)]
        [DisplayName("Close at")]
        public DateTime EndOfTheWorkDay { get; set; }

        [Required]
        public string Description { get; set; }

        [MinLength(2)]
        [MaxLength(512)]
        [DisplayName("Facebook page")]
        public string FacebookPageUrl { get; set; }

        [DisplayName("Destination")]
        [Required]
        public int DestinationId { get; set; }

        [StringLength(10)]
        [DisplayName("Phone number")]
        public string PhoneNumber { get; set; }

        public ICollection<Feature> Features { get; set; } 
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Models/Bars/BindingModels/BarDeleteBindingModel.cs
namespace BarZ.Areas.Bar_reviews.Models.Bars.BindingModels
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public class BarDeleteBindingModel
    {
        [Required]
        public int Id { get; set; }

        public string Name { get; set; }

        [DisplayName("Info:")]
        public string Description { get; set; }

        [DisplayName("Destination:")]
        public string DestinationName { get; set; }

    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Models/Bars/BindingModels/BarUpdateBindingModel.cs
namespace BarZ.Areas.Bar_reviews.Models.Bars.BindingModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    using Microsoft.AspNetCore.Http;

    using BarZ.Data.Models;

    public class BarUpdateBindingModel
    {

        [Required]
        public int Id { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(64)]
        public string Name { get; set; }

        public string PictureAdress { get; set; }

        public IFormFile image { get; set; }

        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Time)]
        [DisplayName("Open at")]
        public DateTime BeginningOfTheWorkDay { get; set; }

        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Time)]
        [DisplayName("Close at")]
        public DateTime EndOfTheWorkDay { get; set; }

        [Required]
        public string Description { get; set; }

        [MinLength(2)]
        [MaxLength(512)]
        [DisplayName("Facebook page")]
        public string FacebookPageUrl { get; set; }

        [DisplayName("Destination")]
        [Required]
        public int DestinationId { get; set; }

        [StringLength(10)]
        [DisplayName("Phone number")]
        public string PhoneNumber { get; set; }

        public virtual ICollection<Feature> Features { get; set; }
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Models/Bars/ViewModels/BarFeatureViewModel.cs
namespace BarZ.Areas.Bar_reviews.Models.Bars.ViewModels
{
    public class BarFeatureViewModel
    {
        public int FeatureId { get; set; }
        public string FeatureName { get; set; }
        public bool Selected { get; set; }
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Models/Bars/ViewModels/BarsViewModel.cs
namespace BarZ.Areas.Bar_reviews.Models.Bars.ViewModels
{
    using System.Collections.Generic;

    public class BarsViewModel
    {
        public IEnumerable<BarViewModel> Bars { get; set; }
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Controllers/BarsController.cs
namespace BarZ.Areas.Bar_reviews.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using BarZ.Areas.Bar_reviews.Models.Bars.BindingModels;
    using BarZ.Areas.Bar_reviews.Models.Bars.ViewModels;
    using BarZ.Areas.Bar_reviews.Models.Destinations.ViewModels;
    using BarZ.Services.Interfaces;
    using BarZ.Data.Models;
    using BarZ.Constants;
    using Microsoft.AspNetCore.Authorization;

    public class BarsController : BarReviewsController
    {
        private readonly IBarsService barsService;
        private readonly IFeaturesService featuresService;
        private readonly IImageService imageService;
        private readonly IDestinationsService destinationsService;

        public BarsController(
            IBarsService barsService, 
            IImageService imageService,
            IDestinationsService destinationsService, 
            IFeaturesService featuresService 
            )
        {
            this.barsService = barsService;
            this.imageService = imageService;
            this.destinationsService = destinationsService;
            this.featuresService = featuresService;
        }
        
        public IActionResult ShowBarsInDestination(int id)
        {
            IEnumerable<BarViewModel> bars = this.barsService.GetAllBarsInDestination(id);      
                
            return this.View(bars);
        }
        public IActionResult ShowBarsByFeature(int id)
        {
            IEnumerable<BarViewModel> bars = this.barsService.ShowBarsByFeature(id);

            return this.View(bars);
        }
        public IActionResult Search()
        {
            return this.View();
        }
        [HttpPost]
        public IActionResult Search(string SearchPhrase)
        {
            if (this.barsService.SearchForABar(SearchPhrase)!=null)
            {
                IEnumerable<BarViewModel> bars = this.barsService.SearchForABar(SearchPhrase);
                if (bars.Any())
                {
                    return this.View("Index", bars);
                }
            }

            return RedirectToAction("Search");
            //TODO: ADD NOTIFICATION FOR BAR WAS NOT FOUND!
            //UPDATE: NOT ENOUGH TIME TO DO THAT...
        }

        // GET: Bars
        public IActionResult Index()
        {
            IEnumerable<BarViewModel> bars = this.barsService.GetAll();

            return this.View(bars);
        }

        // GET: Bars/Details/5
        public IActionResult Details(int? id)
        {
            BarViewModel bar = this.barsService.GetById(id);

            bool isNull = bar == null;
            if (isNull)
            {
                return this.BadRequest();
            }

            return this.View(bar);
        }

        // GET: Bars/Create
        [Authorize]
        public IActionResult Create()
        {
            IEnumerable<IdNameViewModel> destinations = this.destinationsService.GetAll();
            List<Feature> features = this.featuresService.GetAllFeaturesForViewBag().ToList();

            bool areDestinationsEmpty = destinations.Count() == 0;
            if (areDestinationsEmpty)
            {
                return this.RedirectToAction("index");
            }

            ViewBag.Destinations = destinations;
            ViewBag.Features = features;

            return this.View();
            
        }

        // POST: Bars/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(BarCreateBindingModel bar)
        {
             await this.barsService.CreateAsync(bar);

            return this.RedirectToAction("index");
        }

        //GET: Bars/Update/5
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public IActionResult Update(int id)
        {
            BarUpdateBindingModel bar = this.barsService.GetByIdForUpdateMethod(id);
            IEnumerable<IdNameViewModel> destinations = this.destinationsService.GetAll();
      
            bool isBarsNull = bar == null;
            bool areDestinationsEmpty = destinations.Count() == 0;

            if (isBarsNull||areDestinationsEmpty)
            {
                return this.RedirectToAction("index");
            }
        
            var features = barsService.PopulateSelectedFeaturesData(bar);

            ViewBag.Features = features;
            ViewBag.Destinations = destinations;
            return this.View(bar);
        
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public async Task<IActionResult> Update(BarUpdateBindingModel model, string[] selectedFeatures)
        {
            bool isUpdated = await this.barsService.UpdateAsync(model, selectedFeatures);
            if (isUpdated == false)
            {
                return this.BadRequest();
            }
          
            return this.RedirectToAction("index");
        }
        
        [HttpGet]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bar = barsService.GetByIdForDeleteMethod(id);

            if (bar == null)
            {
                return NotFound();
            }

            return View(bar);
        }

        [HttpPost]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.barsService.DeleteAsync(id);

            return this.RedirectToAction("index");
        }
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Controllers/DestinationsController.cs
namespace BarZ.Areas.Bar_reviews.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using BarZ.Areas.Bar_reviews.Models.Destinations.ViewModels;
    using BarZ.Services.Interfaces;
    using BarZ.Areas.Bar_reviews.Models.Destinations.BindingModels;
    using BarZ.Constants;
    using Microsoft.AspNetCore.Authorization;

    public class DestinationsController : BarReviewsController
    {
        private readonly IDestinationsService destinationsService;

        public DestinationsController(IDestinationsService destinationsService)
        {
            this.destinationsService = destinationsService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<IdNameViewModel> destinations = this.destinationsService.GetAll();
            DestinationsViewModel destinationsViewModel = new DestinationsViewModel();

            destinationsViewModel.Destinations = destinations;
           
            return this.View(destinationsViewModel);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var destination = destinationsService.GetByIdForDetailsMethod(id);
            if (destination == null)
            {
                return NotFound();
            }

            return View(destination);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(DestinationCreateBindingModel model)
        {
           
            await destinationsService.CreateAsync(model);
           
            return RedirectToAction("index");
        }

        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public IActionResult Update(int id)
        {
            DestinationUpdateBindingModel destination = this.destinationsService.GetByIdForUpdateMethod(id);
            
            bool isDestinationNull = destination == null;  
            if (isDestinationNull)
            {
                return this.RedirectToAction("index");
            }

            return this.View(destination);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public async Task<IActionResult> Update(DestinationUpdateBindingModel model)
        {
            bool isUpdated = await this.destinationsService.UpdateAsync(model);
            if (isUpdated == false)
            {
                return this.BadRequest();
            }

            return this.RedirectToAction("index");
        }

        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var destination =destinationsService.GetByIdForDeleteMethod(id);
         
            if (destination == null)
            {
                return NotFound();
            }

            return View(destination);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await destinationsService.DeleteAsync(id);

            return RedirectToAction("Index");
        }
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Controllers/EventsController.cs
namespace BarZ.Areas.Bar_reviews.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using BarZ.Services.Interfaces;
    using BarZ.Areas.Bar_reviews.Models.Events.BindingModels;
    using BarZ.Constants;
    using Microsoft.AspNetCore.Authorization;
    using System.Collections.Generic;
    using System.Linq;
    using BarZ.Areas.Bar_reviews.Models.Bars.ViewModels;

    [Area("Bar-reviews")]
    public class EventsController : BarReviewsController
    {
        private readonly IEventsService eventsService;
        private readonly IBarsService barsService;

        public EventsController(IEventsService eventsService, IBarsService barsService)
        {
            this.eventsService = eventsService;
            this.barsService = barsService;
        }

        public IActionResult Index()
        {
            var events = this.eventsService.GetAllFutureEvents();
            return View(events);
        }

        public IActionResult PastEvents()
        {
            var events = this.eventsService.GetAllPastEvents();
            return View(events);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var _event = eventsService.GetById(id);

            if (_event == null)
            {
                return NotFound();
            }

            return View(_event);
        }

        [Authorize]
        public IActionResult Create()
        {
            IEnumerable<BarViewModel> bars = this.barsService.GetAll();

            bool areBarsEmpty = bars.Count() == 0;
            if (areBarsEmpty)
            {
                return this.RedirectToAction("index");
            }

            ViewBag.Bars = bars;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(EventCreateBindingModel model)
        {
            if (ModelState.IsValid)
            {
                await eventsService.CreateAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public IActionResult Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var _event = eventsService.GetByIdForUpdateMethod(id);

            if (_event == null)
            {
                return NotFound();
            }
            return View(_event);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public async Task<IActionResult> UpdateAsync(EventUpdateBindingModel model)
        {
            bool isUpdated = await eventsService.UpdateAsync(model);
            if (isUpdated==false)
            {
                return this.BadRequest();
            }

            return RedirectToAction("Index");
        }

        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var _event = eventsService.GetByIdForDeleteMethod(id);

            if (_event == null)
            {
                return NotFound();
            }

            return View(_event);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RolesConstants.AdminRoleName)]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await eventsService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/Create.cshtml
@model BarCreateBindingModel

@{
    ViewData["Title"] = "Create Bar";
}

<div class="container">
    <div class="halfScreenBox">
        <h1>Create a review</h1>
    </div>
    <div class="halfScreenBox">
        <a class="col-md-4 btn btn-info btnsViewRight" href="##" onClick="history.go(-1); return false;">Go back</a>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input type="file" name="Image" value="" />
            </div>
            <div class="form-group">
                <label asp-for="BeginningOfTheWorkDay" class="control-label"></label>
                <input asp-for="BeginningOfTheWorkDay" class="form-control" />
                <span asp-validation-for="BeginningOfTheWorkDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndOfTheWorkDay" class="control-label"></label>
                <input asp-for="EndOfTheWorkDay" class="form-control" />
                <span asp-validation-for="EndOfTheWorkDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="8"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="FacebookPageUrl" class="control-label"></label>
                <input asp-for="FacebookPageUrl" class="form-control" />
                <span asp-validation-for="FacebookPageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationId" class="control-label"></label>
                <select asp-for="DestinationId" class="form-control">
                    @foreach (var destination in this.ViewBag.Destinations)
                    {
                        <option value="@destination.Id">@destination.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary w-100" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/Delete.cshtml
@model BarDeleteBindingModel

@{
    ViewData["Title"] = "Delete Bar";
}

<br />
<h3>Are you sure you want to delete @Model.Name?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinationName)
        </dd>
    </dl>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form class="halfScreenBox" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirm" class="btn btn-danger w-50" />
    </form>

    <form class="halfScreenBox">
        <a asp-action="Index" class="btn btn-info w-50">Cancel</a>
    </form>

</div>

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/Details.cshtml
@model BarViewModel

@{
    ViewData["Title"] = Model.Name;

}

<div class="container">
    <div class="halfScreenBox">
        <h1>@Html.DisplayFor(model => model.Name)</h1>
    </div>
    <div class="halfScreenBox">
        <a class="col-md-4 btn btn-info btnsViewRight" asp-action="Index">Reviews</a>
    </div>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Work Time
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BeginningOfTheWorkDay) -
            @Html.DisplayFor(model => model.EndOfTheWorkDay)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FacebookPageUrl)
        </dt>
        <dd class="col-sm-10">
            <a href="@Model.FacebookPageUrl">@Html.DisplayFor(model => model.FacebookPageUrl)</a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Destinations"
               asp-action="Details"
               asp-route-id="@Model.Destination.Id"
               class="btn-outline-success">
                @Html.DisplayFor(model => model.Destination.Name)
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <br />
        <br />
        <br />

        <div class="halfScreenBox">
            <h4 class="text-info">Features:</h4>

            @if (this.Model.Features.Any())
            {
                int i = 0;
                string[] features = new string[100];
                foreach (var feature in Model.Features)
                {
                    i++;
                    features[i] = feature.FeatureName;
                }
                var featuresInRow = String.Join(", ", features.Where(s => !string.IsNullOrEmpty(s)));

                <ul>
                    @featuresInRow
                </ul>
            }
            else
            {
                <ul>No Information.</ul>
            }
        </div>

        <div class="halfScreenBox">
            <h4 class="text-info">Events:</h4>

            @if (this.Model.Events.Any())
            {
                @foreach (var item in Model.Events)
                {
                    if (item.DateAndTime > DateTime.UtcNow)
                    {
                        <div style="border:1px solid lightgray; margin:30px; padding:40px">
                            <a asp-controller="Events" asp-action="Details" asp-route-id="@item.Id">
                                <h1 style="margin-top:-20px">@Html.DisplayFor(modelItem => item.EventName)</h1>
                            </a>

                            <div class="font-weight-light">@Html.DisplayFor(modelItem => item.DateAndTime)</div>
                        </div>
                    }
                }
            }
            else
            {
                <span>No Information</span>
            }

        </div>

    </dl>

</div>
@if (this.User.IsInRole(RolesConstants.AdminRoleName))
{
    <div class="btnsViewRight marginBottom100">
        <a class="btn btn-info" asp-action="Update" asp-route-id="@Model.Id">Update</a> |
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    </div>
}

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/Edit.cshtml
@model BarZ.Data.Models.Bar

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Bar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeginningOfTheWorkDay" class="control-label"></label>
                <input asp-for="BeginningOfTheWorkDay" class="form-control" />
                <span asp-validation-for="BeginningOfTheWorkDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndOfTheWorkDay" class="control-label"></label>
                <input asp-for="EndOfTheWorkDay" class="form-control" />
                <span asp-validation-for="EndOfTheWorkDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacebookPageUrl" class="control-label"></label>
                <input asp-for="FacebookPageUrl" class="form-control" />
                <span asp-validation-for="FacebookPageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinationId" class="control-label"></label>
                <select asp-for="DestinationId" class="form-control" asp-items="ViewBag.DestinationId"></select>
                <span asp-validation-for="DestinationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/Index.cshtml
@model IEnumerable<BarViewModel>

@{
    ViewData["Title"] = "Reviews";
}
<div class="container">
    <div class="halfScreenBox">
        <h1 display="inline" class="col-md-4">Reviews</h1>
    </div>
    <div class="halfScreenBox">
        @if (this.User.Identity.IsAuthenticated)
        {
            <a class="col-md-4 btn btn-info btnsViewRight" asp-action="Create">Create a review</a>
        }
    </div>
</div>

<div class="container">
    @foreach (var item in Model)
    {
        <div class="barIndexModel">
            <h2>@Html.DisplayFor(modelItem => item.Name)</h2>
            <p class="font-weight-light">(@Html.DisplayFor(modelItem => item.Destination.Name))</p>

            <img class="rounded mx-auto d-block barPicture" src="@Url.Content(item.PictureAdress)" alt="BarPicture">

            <hr />

            Work time:
            @Html.DisplayFor(modelItem => item.BeginningOfTheWorkDay) -
            @Html.DisplayFor(modelItem => item.EndOfTheWorkDay)<br />

            <hr />
            <span class="description">@Html.DisplayFor(modelItem => item.Description)<br /></span>
            <a href="@Html.DisplayFor(modelItem => item.FacebookPageUrl)">Facebook page</a><br />

            <div class="btnsViewRight">
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                @if (this.User.IsInRole(RolesConstants.AdminRoleName))
                {
                    <span>|</span>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </div>
        </div>
    }
</div>

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/Search.cshtml
@{
    ViewData["Title"] = "Search";
}

<div class="container">
    <div class="halfScreenBox">
        <h1>Search bar by name</h1>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary w-100" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/BarZ/BarZ/Areas/Bar-reviews/Views/Bars/ShowBarsInDestination.cshtml
@model IEnumerable<BarViewModel>

@{
    ViewData["Title"] = "Show Bars in Destination";
}

@{
    string heading = "At the moment there are no bars in here.";

    if (@Model.FirstOrDefault() != null)
    {
        string destination = Model.FirstOrDefault().Destination.Name;
        heading = ($"Bars in {destination}");
    }
}


<div class="container">
    <div class="halfScreenBox">
        <h1>@heading</h1>
    </div>
    <div class="halfScreenBox">
        <a class="col-md-4 btn btn-info btnsViewRight" asp-controller="Destinations" asp-action="Index">Back to destinations</a>
    </div>
</div>

<div class="container">
    @foreach (var item in Model)
    {
        @Html.Partial("ShowBarsWithFeatureOrInDestinationPartialView", item)
    }
</div>